image: golang:1.14

stages:
  - build
  - verify

default:
  before_script:
    - mkdir -p /go/src/gitlab.com/wobcom /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/wobcom/cisco-exporter
    - ln -s /go/src/gitlab.com/wobcom/cisco-exporter /go/src/_/builds/cisco-exporter
    - go get -v -d ./...
    - go build -i -v gitlab.com/wobcom/cisco-exporter
  artifacts:
    paths:
      - /go/src/_/builds/cisco-exporter

compile:
  stage: build
  tags:
    - docker
  script:
    - "true"
  artifacts:
    paths:
      - /go/src/_/builds/cisco-exporter

fmt:
  stage: verify
  tags:
    - docker
  script:
    - test -z $(gofmt -l ./...)

lint:
  stage: verify
  tags:
    - docker
  script:
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status ./...

vet:
  stage: verify
  tags:
    - docker
  script:
    - go vet ./...

test:
  stage: verify
  tags:
    - docker
  script:
    - go test ./...
