image: golang:1.14

tags:
  - docker

stages:
  - verify
  - build
  - publish

default:
  before_script:
    - mkdir -p /go/src/gitlab.com/wobcom /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/wobcom/cisco-exporter
    - ln -s /go/src/gitlab.com/wobcom/cisco-exporter /go/src/_/builds/cisco-exporter
    - go get -v -d ./...
    - go build -o $CI_PROJECT_DIR/cisco-exporter -i -v gitlab.com/wobcom/cisco-exporter

fmt:
  stage: verify
  tags:
    - docker
  script:
    - test -z $(gofmt -l ./...)

lint:
  stage: verify
  tags:
    - docker
  script:
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status ./...

vet:
  stage: verify
  tags:
    - docker
  script:
    - go vet ./...

test:
  stage: verify
  tags:
    - docker
  script:
    - go test ./...

build:
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/cisco-exporter*
  tags:
    - docker
  script:
    - GOOS=linux GOARCH=amd64 go build -o $CI_PROJECT_DIR/cisco-exporter  -i -v gitlab.com/wobcom/cisco-exporter

publish:
  stage: publish
  tags:
    - docker
  only:
    - tags
  script:
    - apt-get update && apt-get install -y jq
    - ./.ci/publish.sh $CI_COMMIT_REF_NAME
